<div class="container-fluid">
    <div class="row mb-5 pb-4 mt-4">
    	<div class="col-12">
    		<form method="post" enctype="multipart/form-data">
    			
    			<input type="text" name="title" placeholder="Nazov videa" value="<?=$view->data["video"]["title"]?>">
    			<br><br>

    			<textarea name="description" placeholder="Popis..."><?=$view->data["video"]["description"]?></textarea>
    			<br><br>

    			<label for="category_id">Kategoria</label>
    			<select id="category_id" name="category_id">
    				<option value="-1" disabled>- Kategoria -</option>
    				<? foreach ($view->data["categories"] as $category) { ?>
    					<option value="<?=$category["id"]?>" <?=($category["id"] == $view->data["video"]["category_id"] ? "selected" : "")?>><?=$category["category"]?></option>
    				<? } ?>
    			</select>
    			<br><br>

    			<label for="author_id">Autor</label>
    			<select id="author_id" name="author_id">
    				<option value="-1" disabled>- Autor videa -</option>
    				<? foreach ($view->data["authors"] as $author) { ?>
    					<option value="<?=$author["id"]?>" <?=($author["id"] == $view->data["video"]["author_id"] ? "selected" : "")?>><?=$author["name"]?></option>
    				<? } ?>
    			</select>
    			<br><br>

    			<button class="btn btn-primary" name="action" value="edit_video" style="font-size:16px">Upravit video</button>

                <input type="hidden" name="video_id" value="<?=$view->data["video"]["id"]?>">
                <button class="btn btn-danger" name="action" value="delete_video" style="font-size:16px">Odstranit video</button>
            </form>
    	</div>
    </div>
</div>