<div class="container-fluid" id="content">
    <div class="row">
        <div class="col-12">
            <h2 class="tm-page-title mb-4">Our Video Catalog</h2>
            <div class="tm-categories-container mb-5">
                <h3 class="tm-text-primary tm-categories-text">Categories:</h3>
                <ul class="nav tm-category-list">
                    <li class="nav-item tm-category-item"><a data-id="-1" href="<?=$config["url"]?>" class="nav-link tm-category-link">All</a></li>
                    <? foreach ($view->data["categories"] as $category) {
                        ?><li class="nav-item tm-category-item"><a data-id="<?=$category["id"]?>" href="<?=($config["url"] . "/?category=" . $category["id"])?>" class="nav-link tm-category-link"><?=$category["category"]?></a></li><?
                    } ?>
                </ul>
            </div>
        </div>
    </div>

    <div class="row tm-catalog-item-list">
        <? foreach ($view->data["videos"] as $video) { ?>
            <div class="col-lg-4 col-md-6 col-sm-12 tm-catalog-item">
                <div class="position-relative tm-thumbnail-container">
                    <img src="<?=$video["thumbnail_url"]?>" alt="Image" class="img-fluid tm-catalog-item-img">    
                    <a href="video-page?video=<?=$video["id"]?>" class="position-absolute tm-img-overlay">
                        <i class="fas fa-play tm-overlay-icon"></i>
                    </a>
                </div>
                <div class="p-4 tm-bg-gray tm-catalog-item-description">
                    <h3 class="tm-text-primary mb-3 tm-catalog-item-title"><?=$video["title"]?></h3>
                    <p class="tm-catalog-item-text"><?=$video["description"]?></p>
                </div>
            </div>
        <? } ?>
    </div>

    <!-- Catalog Paging Buttons -->
    <div>
        <? 
        $category = "";
        if (isset($_GET["category"]) && $_GET["category"] != -1) {
            $category = "&category=" . $_GET["category"];
        }
        $page = 1;
        if (isset($_GET["page"])) {
            $page = $_GET["page"];

            if ($page < 3) {
                $page = 3;
            }
        } else {
            $_GET["page"] = 1;
        } ?>

        <ul class="nav tm-paging-links">
            <li class="nav-item <?=($page - 2 == $_GET["page"] ? "active" : "")?>"><a href="./?page=<?=($page - 2)?><?=$category?>" class="nav-link tm-paging-link"><?=($page - 2)?></a></li>
            <li class="nav-item <?=($page - 1 == $_GET["page"] ? "active" : "")?>"><a href="./?page=<?=($page - 1)?><?=$category?>" class="nav-link tm-paging-link"><?=($page - 1)?></a></li>
            <li class="nav-item <?=($page == $_GET["page"] ? "active" : "")?>"><a href="./?page=<?=($page)?><?=$category?>" class="nav-link tm-paging-link"><?=($page)?></a></li>
            <li class="nav-item <?=($page + 1 == $_GET["page"] ? "active" : "")?>"><a href="./?page=<?=($page + 1)?><?=$category?>" class="nav-link tm-paging-link"><?=($page + 1)?></a></li>
            <li class="nav-item <?=($page + 2 == $_GET["page"] ? "active" : "")?>"><a href="./?page=<?=($page + 2)?><?=$category?>" class="nav-link tm-paging-link"><?=($page + 2)?></a></li>
        </ul>
    </div>
    <script type="text/javascript">
        let categoryLinks = document.querySelectorAll(".tm-category-link");

        for (let i = 0; i < categoryLinks.length; ++i) {
            if (categoryLinks[i].dataset.id == <?=(isset($_GET["category"]) ? $_GET["category"] : -1)?>) {
                categoryLinks[i].classList.add("active");
                break;
            }
        }
    </script>
</div>