<? $video = $view->data["video"]; ?>
<div class="container-fluid">
    <div class="row mb-5 pb-4 mt-4">
    	<div class="col-12">
    		<!-- Video player 1422x800 -->
    		<video width="1422" height="800" controls autoplay>
    		  <source src="<?=$video["url"]?>" type="video/mp4">							  
    		Your browser does not support the video tag.
    		</video>
    	</div>
    </div>
    <div class="row mb-5 pb-5">
    	<div class="col-xl-8 col-lg-7">
    		<!-- Video description -->
    		<div class="tm-video-description-box">
    			<h2 class="mb-5 tm-video-title"><?=$video["title"]?></h2>
    			<p class="mb-4"><?=$video["description"]?></p>	
    		</div>							
    	</div>
    	<div class="col-xl-4 col-lg-5">
    		<!-- Share box -->
    		<div class="tm-bg-gray tm-share-box">
    			<h6 class="tm-share-box-title mb-4">Share this video</h6>
    			<div class="mb-5 d-flex">
    				<a href="" class="tm-bg-white tm-share-button"><i class="fab fa-facebook"></i></a>
    				<a href="" class="tm-bg-white tm-share-button"><i class="fab fa-twitter"></i></a>
    				<a href="" class="tm-bg-white tm-share-button"><i class="fab fa-pinterest"></i></a>
    				<a href="" class="tm-bg-white tm-share-button"><i class="far fa-envelope"></i></a>
    			</div>
    			<p class="mb-4">Author: <a href="<?=$video["author_url"]?>" class="tm-text-link"><?=$video["author"]?></a></p>
    			<a href="./video-page?video=<?=$_GET["video"]?>&action=like" class="tm-bg-white px-5 mb-4 d-inline-block tm-text-primary tm-likes-box tm-liked">
    				<i class="fas fa-heart mr-3 tm-liked-icon"></i>
    				<i class="far fa-heart mr-3 tm-not-liked-icon"></i>
    				<span id="tm-likes-count"><?=$video["likes"]?> likes</span>
    			</a>
    			<div>
    				<a href="<?=$video["url"]?>" target="_blank" download class="btn btn-primary text-light p-0 tm-btn-animate tm-btn-download tm-icon-download"><span>Download Video</span></a>	
    			</div>								
    		</div>
    	</div>
    </div>
    <div class="row pt-4 pb-5">
    	<div class="col-12">
    		<h2 class="mb-5 tm-text-primary">Related Videos for You</h2>
    		<div class="row tm-catalog-item-list">
                <? foreach ($view->data["recommended_videos"] as $video) { ?>
                    <div class="col-lg-4 col-md-6 col-sm-12 tm-catalog-item">
                        <div class="position-relative tm-thumbnail-container">
                            <img src="<?=$video["thumbnail_url"]?>" alt="Image" class="img-fluid tm-catalog-item-img">    
                            <a href="./video-page?video=<?=$video["id"]?>" class="position-absolute tm-img-overlay">
                                <i class="fas fa-play tm-overlay-icon"></i>
                            </a>
                        </div>    
                        <div class="p-3 tm-catalog-item-description">
                            <h3 class="tm-text-gray text-center tm-catalog-item-title"><?=$video["title"]?></h3>                                       
                        </div>
                    </div>                    
                <? } ?>
            </div>
    	</div>
    </div>
</div>